# docker-compose.yml

# version: '3.8'

services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1010
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5435'

volumes:
  postgres:

